name: KOREA

on:
  schedule:
    - cron: "0 */12 * * *"  # Setiap 12 jam
  workflow_dispatch:      # Bisa run manual

permissions:
  contents: write

jobs:
  update_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update.py
        run: python update.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add Aniplus.m3u8 Anibox.m3u8 JTBC.m3u8

          if git diff --staged --quiet; then
            echo "Tidak ada perubahan file m3u8"
          else
            git commit -m "Update Korea playlists"
            git push
          fi
